baseURL = 'https://derjesko.github.io/'
languageCode = 'en-us'
title = 'Jesko Dujmovic'
theme = 'notrack'

[params]
    author = "Jesko Dujmovic"
    favicon = "favicon.png"

    [params.social]
        twitter = "derjesko"
        github = "derjesko"
        email = "jeskowastaken@posteo.net"
